# Generated by Django 4.2.11 on 2024-03-29 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('attempt_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Attempts',
            },
        ),
    ]
