# Generated by Django 4.2.11 on 2024-03-29 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_quizattempt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'ordering': ['-score']},
        ),
    ]
